[tool.poetry]
name = "dptb"
version = "2.0.1"
license = "LGPL-3.0"
description = "A unified deep learning package for electronic structure models including tight-binding, KS Hamiltonian and density matrix models"
readme = "README.md"
repository = "https://github.com/deepmodeling/DeePTB"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "*"
scipy = "*"
matplotlib = "*"
ase = "*"
pyyaml = "*"
dargs = "0.4.4"
e3nn = ">=0.5.1"
torch-runstats = "0.2.0"
opt-einsum = "3.3.0"
h5py = ">=3.7.0,<=3.11.0,!=3.10.0"
lmdb = "1.4.1"
tqdm = "*"
tensorboard = "*"
seekpath = "*"
torch-scatter = "2.1.2"
so2-cuda-ops = { git = "https://github.com/Franklalalala/SO2CUDA.git", branch = "main", optional = true }
openequivariance = { version = "0.6.8", python = ">=3.10", optional = true }

[tool.poetry.extras]
so2 = ["so2-cuda-ops"]
openequi = ["openequivariance"]

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.0"
pytest-order = "1.2.0"
e3nn = ">=0.5.1,<=0.5.3"

[tool.poetry.scripts]
dptb = 'dptb.__main__:main'

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
strict = false
format-jinja = """
    {%- if distance == 0 -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance, metadata=[commit]) }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base), stage, revision, dev=distance, metadata=[commit]) }}
    {%- endif -%}
"""
