from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

import numpy as np
from scipy.fft import next_fast_len
from scipy.special import erf

from .constants import E2_RY_BOHR, FOUR_PI
from .models import SpeciesData, Structure
from .radial_quadrature import simpson_rab
from .xc import lda_pz81_vxc_ry, pbe_vxc_ry
from .structure_factor import gaussian_structure_factor, gaussian_nufft_parameters


def choose_fft_shape(
    cell_bohr: np.ndarray,
    ecutrho_ry: float,
    minimum: int = 12,
) -> tuple[int, int, int]:
    """Choose a conservative fallback FFT shape for ``|G|^2 <= ecutrho``.

    This is only a fallback for exploratory runs.  For an oblique cell, the
    maximum reciprocal *index* along axis ``i`` inside a sphere of radius
    ``Gmax`` is bounded by ``Gmax |a_i| / (2 pi)``.  Using direct-lattice row
    lengths therefore avoids the incorrect reciprocal-row-norm heuristic.  A
    code-to-code production run must still pass the exact ABACUS FFT shape.
    """
    cell = np.asarray(cell_bohr, dtype=float)
    if cell.shape != (3, 3):
        raise ValueError("cell_bohr must have shape (3,3)")
    if ecutrho_ry <= 0.0:
        raise ValueError("ecutrho_ry must be positive")
    gmax = np.sqrt(float(ecutrho_ry))
    shape: list[int] = []
    for direct_length in np.linalg.norm(cell, axis=1):
        nmax = int(np.ceil(gmax * direct_length / (2.0 * np.pi)))
        # 2*nmax+1 represents both signs plus zero without a Nyquist ambiguity.
        shape.append(int(next_fast_len(max(int(minimum), 2 * nmax + 1))))
    return tuple(shape)


def reciprocal_grid(cell_bohr: np.ndarray, shape: tuple[int, int, int]):
    b = 2.0 * np.pi * np.linalg.inv(np.asarray(cell_bohr, dtype=float)).T
    freq = [np.fft.fftfreq(n, d=1.0 / n) for n in shape]
    h, k, l = np.meshgrid(*freq, indexing="ij")
    gvec = h[..., None] * b[0] + k[..., None] * b[1] + l[..., None] * b[2]
    g2 = np.einsum("...i,...i->...", gvec, gvec)
    return gvec, g2


def _unique_magnitudes(
    g2: np.ndarray,
    *,
    round_decimals: int | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Deduplicate reciprocal magnitudes without a hidden accuracy rounding.

    ``round_decimals`` is an explicit exploratory speed knob.  Strict/default
    reconstruction keeps the exact floating magnitudes generated by the grid.
    """
    flat = np.sqrt(np.maximum(g2.ravel(), 0.0))
    values = flat if round_decimals is None else np.round(flat, int(round_decimals))
    return np.unique(values, return_inverse=True)


def radial_charge_transform(
    q: np.ndarray,
    r: np.ndarray,
    rab: np.ndarray,
    g: np.ndarray,
) -> np.ndarray:
    """Return ``Q(G)=integral q(r) sinc(G r) dr`` for UPF ``PP_RHOATOM``.

    ``q(r)=4*pi*r^2*rho(r)`` and integration uses the UPF ``PP_RAB`` Jacobian
    with exactly the same composite-Simpson coefficients as ABACUS.
    """
    q = np.asarray(q, dtype=float)
    r = np.asarray(r, dtype=float)
    rab = np.asarray(rab, dtype=float)
    g = np.asarray(g, dtype=float)
    if q.shape != r.shape or rab.shape != r.shape:
        raise ValueError("q, r, and PP_RAB must have identical one-dimensional shapes")
    out = np.empty_like(g)
    for start in range(0, len(g), 256):
        gg = g[start : start + 256, None]
        kernel = np.sinc((gg * r[None, :]) / np.pi)
        out[start : start + len(gg)] = simpson_rab(q[None, :] * kernel, rab, axis=1)
    return out


def radial_density_transform(
    rho: np.ndarray,
    r: np.ndarray,
    rab: np.ndarray,
    g: np.ndarray,
) -> np.ndarray:
    """Fourier transform of a spherical radial density ``rho(r)``."""
    return radial_charge_transform(FOUR_PI * r**2 * np.asarray(rho), r, rab, g)


def radial_vloc_transform(
    vloc_ry: np.ndarray,
    r: np.ndarray,
    rab: np.ndarray,
    z_valence: float,
    g: np.ndarray,
    volume: float,
    keep_g0_alpha: bool,
) -> np.ndarray:
    """ABACUS local-pseudopotential Fourier coefficients.

    The Coulomb tail is regularized with ``erf(r)`` as in ABACUS
    ``pseudopot_cell_vl::vloc_of_g``.  At ``G=0`` the finite alpha term is
    retained when requested.  Every radial integral uses ``PP_RAB`` rather than
    re-integrating against the displayed ``PP_R`` coordinates.
    """
    vloc = np.asarray(vloc_ry, dtype=float)
    r = np.asarray(r, dtype=float)
    rab = np.asarray(rab, dtype=float)
    g = np.asarray(g, dtype=float)
    if vloc.shape != r.shape or rab.shape != r.shape:
        raise ValueError("vloc, r, and PP_RAB must have identical shapes")
    z_e2 = z_valence * E2_RY_BOHR
    compensated = r * vloc + z_e2 * erf(r)
    out = np.zeros_like(g)
    zero = g < 1e-13
    if np.any(zero) and keep_g0_alpha:
        alpha = simpson_rab(r * (r * vloc + z_e2), rab)
        out[zero] = FOUR_PI * alpha / volume
    nz_idx = np.where(~zero)[0]
    for start in range(0, len(nz_idx), 256):
        ids = nz_idx[start : start + 256]
        gg = g[ids, None]
        integ = simpson_rab(
            compensated[None, :] * np.sin(gg * r[None, :]) / gg,
            rab,
            axis=1,
        )
        analytic = z_e2 * np.exp(-(g[ids] ** 2) / 4.0) / (g[ids] ** 2)
        out[ids] = FOUR_PI * (integ - analytic) / volume
    return out


def _structure_factor(gvec: np.ndarray, positions: np.ndarray) -> np.ndarray:
    flat_g = gvec.reshape(-1, 3)
    phase = flat_g @ positions.T
    return np.exp(-1j * phase).sum(axis=1).reshape(gvec.shape[:-1])


def _ifft_series(coeff: np.ndarray) -> np.ndarray:
    return (np.fft.ifftn(coeff) * coeff.size).real


@dataclass
class PeriodicField:
    cell_bohr: np.ndarray
    values_ry: np.ndarray
    rho: np.ndarray
    vloc_ry: np.ndarray
    vh_ry: np.ndarray
    vxc_ry: np.ndarray
    rho_g: np.ndarray
    gvec: np.ndarray
    metadata: dict[str, object]

    @property
    def shape(self) -> tuple[int, int, int]:
        return tuple(int(n) for n in self.values_ry.shape)

    @property
    def grid_weight(self) -> float:
        return float(abs(np.linalg.det(self.cell_bohr)) / np.prod(self.shape))

    def interpolate(self, points_bohr: np.ndarray) -> np.ndarray:
        """Periodic trilinear interpolation at Cartesian points.

        This remains available for diagnostics.  Production local-potential AO
        contraction uses the exact periodic FFT nodes in ``quadrature.py`` and
        therefore does not call this interpolator.
        """
        points = np.asarray(points_bohr, dtype=float)
        frac = points @ np.linalg.inv(self.cell_bohr)
        frac = frac - np.floor(frac)
        shape = np.asarray(self.shape, dtype=int)
        u = frac * shape
        i0 = np.floor(u).astype(int) % shape
        t = u - np.floor(u)
        out = np.zeros(len(points), dtype=float)
        for dx in (0, 1):
            wx = (1.0 - t[:, 0]) if dx == 0 else t[:, 0]
            ix = (i0[:, 0] + dx) % shape[0]
            for dy in (0, 1):
                wy = (1.0 - t[:, 1]) if dy == 0 else t[:, 1]
                iy = (i0[:, 1] + dy) % shape[1]
                for dz in (0, 1):
                    wz = (1.0 - t[:, 2]) if dz == 0 else t[:, 2]
                    iz = (i0[:, 2] + dz) % shape[2]
                    out += wx * wy * wz * self.values_ry[ix, iy, iz]
        return out


def build_periodic_field(
    structure: Structure,
    species_data: Mapping[str, SpeciesData],
    *,
    ecutrho_ry: float,
    fft_shape: tuple[int, int, int] | None = None,
    xc: str = "LDA_PZ81",
    hartree_g0: str | float = "zero",
    local_g0: str = "alpha",
    include_nlcc: bool = True,
    total_electrons: float | None = None,
    radial_g_round_decimals: int | None = None,
    pbe_density_threshold: float = 1.0e-6,
    structure_factor_backend: str = "direct",
    structure_factor_eps: float = 1.0e-12,
    structure_factor_max_work_mb: float | None = 512.0,
    structure_factor_nthreads: int = 1,
    field_backend: str = "numpy",
    compute_device: str = "cpu",
    field_max_work_mb: float | None = 1024.0,
) -> PeriodicField:
    if fft_shape is None:
        fft_shape = choose_fft_shape(structure.cell_bohr, ecutrho_ry)
    fft_shape = tuple(int(v) for v in fft_shape)
    if len(fft_shape) != 3 or any(v <= 0 for v in fft_shape):
        raise ValueError(f"fft_shape must contain three positive integers, got {fft_shape}")
    sf_backend = str(structure_factor_backend).lower()
    if sf_backend not in {"direct", "gaussian_nufft", "finufft", "cufinufft", "torch_gaussian"}:
        raise ValueError("Unknown structure_factor_backend")
    field_backend = str(field_backend).lower()
    if field_backend not in {"numpy", "torch"}:
        raise ValueError("field_backend must be 'numpy' or 'torch'")
    if field_backend == "torch":
        from .torch_fields import build_periodic_field_torch
        return build_periodic_field_torch(
            structure, species_data, ecutrho_ry=ecutrho_ry, fft_shape=fft_shape,
            xc=xc, hartree_g0=hartree_g0, local_g0=local_g0, include_nlcc=include_nlcc,
            total_electrons=total_electrons, radial_g_round_decimals=radial_g_round_decimals,
            pbe_density_threshold=pbe_density_threshold, structure_factor_backend=sf_backend,
            structure_factor_eps=structure_factor_eps,
            structure_factor_max_work_mb=structure_factor_max_work_mb,
            compute_device=compute_device, field_max_work_mb=field_max_work_mb)
    if str(compute_device) != "cpu" or sf_backend in {"cufinufft", "torch_gaussian"}:
        raise ValueError("NumPy fields require CPU and direct/gaussian_nufft/finufft; use field_backend='torch' for torch/CUDA")
    if sf_backend == "gaussian_nufft":
        # Validate the approximation and memory budget before allocating fields.
        gaussian_nufft_parameters(fft_shape, structure_factor_eps, structure_factor_max_work_mb)
    gvec, g2 = reciprocal_grid(structure.cell_bohr, fft_shape)
    gmag_unique, inverse = _unique_magnitudes(
        g2, round_decimals=radial_g_round_decimals
    )
    mask = g2 <= float(ecutrho_ry) + 1e-12
    volume = structure.volume
    positions = structure.cart_positions

    rho_g = np.zeros(fft_shape, dtype=complex)
    rho_core_g = np.zeros(fft_shape, dtype=complex)
    vloc_g = np.zeros(fft_shape, dtype=complex)

    atom_species = np.asarray([a.species for a in structure.atoms], dtype=object)
    fractional_positions = np.asarray([a.frac for a in structure.atoms], dtype=float)
    sf_stats: dict[str, object] = {}
    for symbol in sorted(species_data):
        data = species_data[symbol]
        ids = np.where(atom_species == symbol)[0]
        if ids.size == 0:
            continue
        if sf_backend == "direct":
            sf = _structure_factor(gvec, positions[ids])
            sf_stats[symbol] = {"atoms": int(ids.size), "dense_phase_elements": int(g2.size * ids.size)}
        elif sf_backend == "finufft":
            from .nufft_backends import library_structure_factor
            sf, sf_stats[symbol] = library_structure_factor(
                fractional_positions[ids], fft_shape, backend="finufft",
                eps=structure_factor_eps, nthreads=structure_factor_nthreads,
                max_work_mb=structure_factor_max_work_mb,
            )
        else:
            sf, sf_stats[symbol] = gaussian_structure_factor(
                fractional_positions[ids], fft_shape,
                eps=structure_factor_eps, max_work_mb=structure_factor_max_work_mb,
            )
        upf = data.upf
        qg_unique = radial_charge_transform(upf.rhoatom_q, upf.r, upf.rab, gmag_unique)
        qg = qg_unique[inverse].reshape(fft_shape)
        rho_g += sf * qg / volume

        vg_unique = radial_vloc_transform(
            upf.vloc_ry,
            upf.r,
            upf.rab,
            upf.z_valence,
            gmag_unique,
            volume,
            keep_g0_alpha=(local_g0.lower() == "alpha"),
        )
        vloc_g += sf * vg_unique[inverse].reshape(fft_shape)

        if include_nlcc and upf.nlcc is not None:
            if upf.nlcc_is_radial_density:
                cg_unique = radial_density_transform(upf.nlcc, upf.r, upf.rab, gmag_unique)
            else:
                cg_unique = radial_charge_transform(upf.nlcc, upf.r, upf.rab, gmag_unique)
            rho_core_g += sf * cg_unique[inverse].reshape(fft_shape) / volume

    rho_g = np.where(mask, rho_g, 0.0)
    rho_core_g = np.where(mask, rho_core_g, 0.0)

    # ABACUS rescales the complete superposed valence density to the requested
    # electron count after the reciprocal-to-real transform.  Neutral is the
    # default for this interface.
    if total_electrons is None:
        total_electrons = float(
            sum(species_data[a.species].upf.z_valence for a in structure.atoms)
        )
    raw_electrons = float(rho_g[(0, 0, 0)].real * volume)
    if raw_electrons <= 0.0:
        raise ValueError(
            f"Superposed PP_RHOATOM has non-positive electron count {raw_electrons}"
        )
    density_scale = float(total_electrons) / raw_electrons
    rho_g *= density_scale
    vloc_g = np.where(mask, vloc_g, 0.0)
    if local_g0.lower() == "zero":
        vloc_g[(0, 0, 0)] = 0.0
    elif local_g0.lower() != "alpha":
        raise ValueError("local_g0 must be 'alpha' or 'zero'")

    vh_g = np.zeros_like(rho_g)
    nonzero = g2 > 1e-14
    vh_g[nonzero] = FOUR_PI * E2_RY_BOHR * rho_g[nonzero] / g2[nonzero]
    if isinstance(hartree_g0, str):
        if hartree_g0.lower() != "zero":
            raise ValueError(
                "hartree_g0 must be 'zero' (ABACUS gauge) or a numeric constant potential in Ry"
            )
        vh_g[(0, 0, 0)] = 0.0
    else:
        vh_g[(0, 0, 0)] = float(hartree_g0)

    rho = _ifft_series(rho_g)
    # XC functionals are undefined for negative densities. Fourier truncation
    # can create tiny negative ripples; floor only the XC input.
    rho_xc_raw = _ifft_series(rho_g + rho_core_g)
    rho_xc = np.maximum(rho_xc_raw, 1.0e-30)
    vloc = _ifft_series(vloc_g)
    vh = _ifft_series(vh_g)

    xc_upper = xc.upper()
    if xc_upper in {"LDA", "LDA_PZ81", "PZ81"}:
        vxc = lda_pz81_vxc_ry(rho_xc)
    elif xc_upper in {"PBE", "GGA_PBE"}:
        grad = []
        for axis in range(3):
            grad_g = 1j * gvec[..., axis] * (rho_g + rho_core_g)
            grad.append(_ifft_series(grad_g))
        vxc = pbe_vxc_ry(
            rho_xc,
            tuple(grad),
            gvec,
            density_threshold=float(pbe_density_threshold),
            pw_mask=np.sum(gvec*gvec,axis=-1)<=float(ecutrho_ry)+1e-12,
        )
    elif xc_upper in {"NONE", "OFF"}:
        vxc = np.zeros_like(rho)
    else:
        raise ValueError(f"Unsupported XC option: {xc}")

    total = vloc + vh + vxc
    return PeriodicField(
        cell_bohr=np.asarray(structure.cell_bohr),
        values_ry=total,
        rho=rho,
        vloc_ry=vloc,
        vh_ry=vh,
        vxc_ry=vxc,
        rho_g=rho_g,
        gvec=gvec,
        metadata={
            "field_backend": "numpy",
            "compute_device": "cpu",
            "structure_factor_backend": sf_backend,
            "structure_factor_eps": float(structure_factor_eps) if sf_backend != "direct" else None,
            "structure_factor_stats": sf_stats,
            "ecutrho_ry": float(ecutrho_ry),
            "fft_shape": list(fft_shape),
            "fft_grid_origin_fractional": [0.0, 0.0, 0.0],
            "radial_quadrature": "ABACUS composite Simpson with PP_RAB",
            "xc": xc,
            "hartree_g0": hartree_g0,
            "local_g0": local_g0,
            "include_nlcc": include_nlcc,
            "target_electrons": float(total_electrons),
            "raw_superposed_electrons": raw_electrons,
            "density_normalization_scale": density_scale,
            "radial_g_round_decimals": radial_g_round_decimals,
            "pbe_density_threshold_electrons_per_bohr3": (
                float(pbe_density_threshold) if xc_upper in {"PBE", "GGA_PBE"} else None
            ),
            "minimum_valence_density_on_fft_grid": float(np.min(rho)),
            "minimum_xc_density_before_floor": float(np.min(rho_xc_raw)),
        },
    )
