name: DeePTB tests.

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      
jobs: 
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'deepmodeling'
    container: ghcr.io/deepmodeling/deeptb:latest
    steps: 
      - name: Checkout
        id: s1
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Add safe directory
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Run behavioral smoke suite
        id: s2
        run: |
         bash ut.sh
